BIT_SIZE = 32
FRACTIONAL_BITS_REQUIRED = 19
POSITIVE_SIGN = 0
NEGATIVE_SIGN = 1
MAX_VALUE = (1 << (BIT_SIZE - 1)) - 1
MIN_VALUE = -(1 << (BIT_SIZE - 1))

# IEEE-754 (32 bit) Constants
FLOAT_BIT_SIZE = 32
FLOAT_EXP_BITS = 8
FLOAT_MANTISSA_BITS = 23
FLOAT_BIAS = 127
IEEE_FLOAT_EXP_LIMIT = 255
FLOAT_SIGNIFICAND_BITS = FLOAT_MANTISSA_BITS + 1
FLOAT_PRODUCT_BITS = FLOAT_SIGNIFICAND_BITS * 2
ROUNDING_SHIFT_WITH_LEADING_ONE = 1