"""Project-wide constants."""

MAX_VARIABLE_COUNT = 5
MIN_VARIABLE_COUNT = 1
MAX_KARNAUGH_VARIABLE_COUNT = 5
SUPPORTED_VARIABLES = ("a", "b", "c", "d", "e")

TOKEN_NOT = "NOT"
TOKEN_AND = "AND"
TOKEN_OR = "OR"
TOKEN_IMPLIES = "IMPLIES"
TOKEN_EQUIV = "EQUIV"
TOKEN_LPAREN = "LPAREN"
TOKEN_RPAREN = "RPAREN"
TOKEN_VARIABLE = "VARIABLE"
TOKEN_END = "END"

OPERATOR_PRIORITY = {
    TOKEN_EQUIV: 1,
    TOKEN_IMPLIES: 2,
    TOKEN_OR: 3,
    TOKEN_AND: 4,
    TOKEN_NOT: 5,
}
